
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install git+https://git.openstack.org/openstack/neutron.git@2014.2.2
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
# command to run tests
script: nosetests
